### ISSUE TITLE
Ничейный исход

### ISSUE THREAD

**Issue by M-Sh-97** [snets0711/kr2015#1]
Если игра заканчивается ничейно, то ничего не происходит. Ожидается то, что - при победе / поражении.

**Comment by snets0711** [comment]
Данный баг наблюдается.Будет исправлен в ближайшее время

**Comment by M-Sh-97** [comment]
Результат обрабатывается там же, где и любое нажатие на поле игры, то есть в методе Button ClickAction.actionPerformed(ActionEvent e). Нужно там что-то дополнить.

**Comment by M-Sh-97** [comment]
Создай в GameBoard поле, в котором будет хранится количество заполненных ячеек либо состояние полного заполнения.
После этого в указанном выше методе используй её значение (через get'тер) после равного null результата GameBoard.getNextWinner(int winCount).

**Comment by snets0711** [comment]
Исправлено.

**Comment by M-Sh-97** [comment]
Да, стало лучше. Однако не вижу смысла не выбирать продолжение игры, ибо в таком случае попаду в тот же изначальный тупик.
При другом исходе такой выбор не предлагается. Считаю, что для ничьи нужно того же вида уведомление, что и для победы-поражения, только с предложением не о победителе партии.

**Comment by snets0711** [comment]
Исправлено.Тема закрыта.

**Comment by M-Sh-97** [comment]
"Начать новую игру" и "Сбросить счёт" почти полностью повторяют друг друга. Достаточно того, чтобы всегда после оконченного розыгрыша и уведомления (без выбора) начинался новый, а в меню "Игра" был пункт о сбросе счёта.
Не вижу смысла в возможности не начинать новый розыгрыш при ничьей: она ведь не предлагается при другом результате.
По-прежнему в сообщении о ничьей не напоминается счёт.

**Comment by M-Sh-97** [comment]
Показывать в счёте количество ничьих - хорошая мысль.
Только сделай так, чтобы и в случае победы-поражения их количество отображалось.

**Comment by snets0711** [comment]
По идее там все есть.Только вот размера диалогового окна не хватает для отображения)

**Comment by M-Sh-97** [comment]
Выбор меню текущий счёт: "Score: X (?), O (?)_, draws: ?_".
Ничейный розыгрыш: "Draw.Score: Player 1: X(?)-Player 2: O(?)_ Draws: ?_".
Выигрыш / проигрыш: "Player ? won! Score: Player 1: X(?)-Player 2: O(?)".
Не хватает!

**Comment by snets0711** [comment]
Фак(
